### ISSUE TITLE
Please improve the makefile

### ISSUE THREAD

**Issue by yurivict** [waywardgeek/sonic#16]
Several items that can be improved:
* Don't hardcode gcc: you should use $(CC)
* Every linking line needs $(LDFLAGS)
* The executable could link against te shared library, not static library
* No need to build/install the static library

**Comment by waywardgeek** [comment]
Hi, Yuri.  These are reasonable suggestions.  Would you have time to submit a pull request?

**Comment by ryandesign** [comment]
> * Don't hardcode gcc: you should use $(CC)

The Makefile already uses $(CC) since 0ad5c271c9c3fa54db205ad3536497785eba2b22 in 2010 however it also sets CC=gcc which it should not do since make surely already provides a reasonable default and the user may wish to override it with an environment variable. This line was removed as part of eebb020958f0fa84ee831a55f7158cee8d108819 in 2020 but then re-added in db5c2d3afa7088c88a497e8d07a8b7048d65601f in 2021. It should be removed again.

> * Every linking line needs $(LDFLAGS)

This was done in db5c2d3afa7088c88a497e8d07a8b7048d65601f in 2021. It was not done for libsonic.a but I don't know whether a static library would benefit from LDFLAGS.

> * The executable could link against te shared library, not static library

The executable did used to link with the shared library but was changed to link with the static library in 6a16cb35a28d26aa449c62bd91acf6f2526989a8 in 2016 without explanation. Unless there was a good reason for the change I agree it should be switched back. If it is, the newly-added `check` target will need to be fixed to find the shared (Linux)/dynamic (Mac) library in the build tree; for Mac, setting the environment variable `DYLD_LIBRARY_PATH=.` should fix that; for Linux it's presumably `LD_LIBRARY_PATH-.`.

> No need to build/install the static library

There might be valid uses of a static library. It does no harm to build and install it. In autotools-based projects it is not uncommon for both static and shared libraries to be built and installed. However in most cmake-based projects it is only possible to build either static or shared libraries and most packagers would choose to provide the shared library in that case.

**Comment by yurivict** [comment]
I am glad that things changed in the past 3 years.
